AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  DigestTweet:
    Type: String
  DigestRetweet:
    Type: String
  BatchSize:
    Type: String
    Default: 10
  ScheduleExpression:
    Type: String
    Default: rate(10 minutes) 
Resources:
  QueueSQS:
    Type: AWS::SQS::Queue
    Properties:
      DelaySeconds: 3
      MaximumMessageSize: 262144
      MessageRetentionPeriod: 600
      ReceiveMessageWaitTimeSeconds: 1
      VisibilityTimeout: 30
  BucketS3:
    Type: "AWS::S3::Bucket"
    DependsOn: SQSQueuePolicy
    Properties:
      PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true
      NotificationConfiguration:
        QueueConfigurations:
          - Event: "s3:ObjectCreated:*"
            Queue: !GetAtt QueueSQS.Arn
            Filter:
              S3Key:
                Rules:
                  - Name: "prefix"
                    Value: "tweets/"
                  - Name: "suffix"
                    Value: ".json"
  SQSQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: 
              AWS: "*"
            Action: 
              - sqs:*
            Resource: !GetAtt QueueSQS.Arn
            Condition:
              StringEquals:
                aws:SourceAccount: !Ref AWS::AccountId
      Queues: 
        - !Ref QueueSQS
  BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref BucketS3
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowSSLRequestsOnly
            Effect: Deny
            Principal: '*'
            Action: 's3:*'
            Resource:
              - !GetAtt 'BucketS3.Arn'
              - !Sub '${BucketS3.Arn}/*'
            Condition:
              Bool:
                'aws:SecureTransport': false
  LambdaFunctionTweets:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: mlops-bot-tweets
      Role: !GetAtt LambdaFunctionTweetsRole.Arn
      PackageType: Image
      Code:
        ImageUri: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/mlopsbot/tweets@${DigestTweet}
      Timeout: 30
      Environment: 
         Variables: 
            BUCKET: !Ref BucketS3
  LambdaFunctionTweetsRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: mlops-bot-tweets-policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: 
                  - "cloudwatch:*"
                  - "ec2:DescribeSecurityGroups"
                  - "ec2:DescribeSubnets"
                  - "ec2:DescribeVpcs"
                  - "events:*"
                  - "iam:GetPolicy"
                  - "iam:GetPolicyVersion"
                  - "iam:GetRole"
                  - "iam:GetRolePolicy"
                  - "iam:ListAttachedRolePolicies"
                  - "iam:ListRolePolicies"
                  - "iam:ListRoles"
                  - "iam:PassRole"
                  - "kms:ListAliases"
                  - "lambda:*"
                  - "logs:*"
                  - "s3:*"
                  - "secretsmanager:*"
                  - "sns:ListSubscriptions"
                  - "sns:ListSubscriptionsByTopic"
                  - "sns:ListTopics"
                  - "sns:Publish"
                  - "sns:Subscribe"
                  - "sns:Unsubscribe"
                  - "sqs:ListQueues"
                  - "sqs:SendMessage"
                  - "tag:GetResources"
                Resource: '*'
      MaxSessionDuration: 3600
  LambdaFunctionRetweets:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: mlops-bot-retweets
      Role: !GetAtt LambdaFunctionRetweetsRole.Arn
      PackageType: Image
      Code:
        ImageUri: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/mlopsbot/retweets@${DigestRetweet}
      Timeout: 30
  LambdaFunctionRetweetsRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: mlops-bot-tweets-ssm-policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: 
                  - ssm:GetParameter
                  - ssm:GetParameters
                Resource: !Sub
                  - arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${bucket_parameter}"
                  - { bucket_parameter: !Ref BucketParameter }
        - PolicyName: mlops-bot-tweets-policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: 
                  - "cloudwatch:*"
                  - "ec2:DescribeSecurityGroups"
                  - "ec2:DescribeSubnets"
                  - "ec2:DescribeVpcs"
                  - "events:*"
                  - "iam:GetPolicy"
                  - "iam:GetPolicyVersion"
                  - "iam:GetRole"
                  - "iam:GetRolePolicy"
                  - "iam:ListAttachedRolePolicies"
                  - "iam:ListRolePolicies"
                  - "iam:ListRoles"
                  - "iam:PassRole"
                  - "kms:ListAliases"
                  - "lambda:*"
                  - "logs:*"
                  - "s3:*"
                  - "secretsmanager:*"
                  - "sns:ListSubscriptions"
                  - "sns:ListSubscriptionsByTopic"
                  - "sns:ListTopics"
                  - "sns:Publish"
                  - "sns:Subscribe"
                  - "sns:Unsubscribe"
                  - "sqs:ListQueues"
                  - "sqs:SendMessage"
                  - "tag:GetResources"
                  - "sqs:*"
                Resource: '*'
      MaxSessionDuration: 3600 
  LambdaFunctionEventSourceMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: !Ref BatchSize
      Enabled: true
      EventSourceArn: !GetAtt QueueSQS.Arn
      FunctionName: !GetAtt LambdaFunctionRetweets.Arn
  ScheduledRule: 
    Type: AWS::Events::Rule
    Properties: 
      Description: "ScheduledRule"
      ScheduleExpression: !Ref ScheduleExpression
      State: "ENABLED"
      Targets: 
        - 
          Arn: 
            Fn::GetAtt: 
              - "LambdaFunctionTweets"
              - "Arn"
          Id: "TargetFunctionV1"
  PermissionForEventsToInvokeLambda: 
    Type: AWS::Lambda::Permission
    Properties: 
      FunctionName: !Ref LambdaFunctionTweets
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn: 
        Fn::GetAtt: 
          - "ScheduledRule"
          - "Arn"
  BucketParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /CloudAtlas/MLOpsBot/Bucket
      Type: String
      Value: !Ref BucketS3
      Description: MLOps Bot S3 Bucket