name: ML Lambda Container Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:      
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials from your account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Build and Push Image - Get Tweets
        run: |
          export REPO_NAME_TWEETS=mlopsbot/tweets
          aws ecr describe-repositories --repository-names ${REPO_NAME_TWEETS} || aws ecr create-repository --repository-name ${REPO_NAME_TWEETS}
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com
          cd lambdaTweet && docker build -t ${REPO_NAME_TWEETS} . && cd ..
          docker tag ${REPO_NAME_TWEETS}:latest ${{ secrets.ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/${REPO_NAME_TWEETS}:latest
          docker push ${{ secrets.ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/${REPO_NAME_TWEETS}:latest

      - name: Build and Push Image - Retweets
        run: |
          export REPO_NAME_RETWEETS=mlopsbot/retweets
          aws ecr describe-repositories --repository-names ${REPO_NAME_RETWEETS} || aws ecr create-repository --repository-name ${REPO_NAME_RETWEETS}
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com
          cd lambdaRetweet && docker build -t ${REPO_NAME_RETWEETS} . && cd ..
          docker tag ${REPO_NAME_RETWEETS}:latest ${{ secrets.ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/${REPO_NAME_RETWEETS}:latest
          docker push ${{ secrets.ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/${REPO_NAME_RETWEETS}:latest


        

      # - name: Create or update lambda function
      #   run: | 
      #     aws cloudformation deploy \
      #       --stack-name discovery-lambda-stack \
      #       --template-file lambda.yml \
      #       --capabilities CAPABILITY_NAMED_IAM
