name: MLOps Bot Deploy
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  TweetImagePush:
    runs-on: ubuntu-20.04
    env:
      AWS_REGION: us-east-1
      ECR_REPO: mlopsbot/tweets
      DOCKER_CTX: app/lambdaTweet
    steps:      
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS credentials from your account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Tweet Collection Image Build
        run: | 
          ./scripts/build_push.sh \
            -r ${{ env.ECR_REPO }} \
            -a ${{ secrets.ACCOUNT_ID }} \
            -c ${{ env.DOCKER_CTX }} \
            -g ${{ env.AWS_REGION }}
  RetweetImagePush:
    runs-on: ubuntu-20.04
    env:
      AWS_REGION: us-east-1
      ECR_REPO: mlopsbot/retweets
      DOCKER_CTX: app/lambdaRetweet
    steps:      
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS credentials from your account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Retweet Lambda Image Build Test
        run: | 
          ./scripts/build_push.sh \
            -r ${{ env.ECR_REPO }} \
            -a ${{ secrets.ACCOUNT_ID }} \
            -c ${{ env.DOCKER_CTX }} \
            -g ${{ env.AWS_REGION }}
  DeployMlopsBot:
    needs: [TweetImagePush, RetweetImagePush]
    runs-on: ubuntu-20.04
    env:
      AWS_REGION: us-east-1
      ECR_TWEET: mlopsbot/tweets
      ECR_RETWEET: mlopsbot/retweets
      STACK_NAME: mlops-bot
      CFN_FILE: infra/cloudformation.yaml
    steps:      
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS credentials from your account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Create or update lambda function
        run: |
          export DIG_TWEET=$(./scripts/image_digest.sh -r ${{ env.ECR_TWEET }})
          export DIG_RETWEET=$(./scripts/image_digest.sh -r ${{ env.ECR_RETWEET }})
          echo $DIG_TWEET
# export DIG_TWEET=$(./scripts/image_digest.sh -r ${{ env.ECR_TWEET }})
# export DIG_RETWEET=$(./scripts/image_digest.sh -r ${{ env.ECR_RETWEET }})
# aws cloudformation deploy \
#   --stack-name ${{ env.STACK_NAME }}) \
#   --template-file ${{ env.CFN_FILE }} \
#   --capabilities CAPABILITY_NAMED_IAM \
#   --parameter-overrides \
#       DigestTweet=$DIG_TWEET \
#       DigestRetweet=$DIG_RETWEET
