name: Test and Validation
on:
  push:
    branches: [ develop ]
jobs:
  build-tweet:
    runs-on: ubuntu-20.04
    env:
      AWS_REGION: us-east-1
      ECR_REPO: mlopsbot/tweets
      DOCKER_CTX: app/lambdaTweet
    steps:      
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS credentials from your account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Tweet Collection Image Build
        run: | 
          ./scripts/build_push.sh \
            -r ${{ env.ECR_REPO }} \
            -a ${{ secrets.ACCOUNT_ID }} 
            -c ${{ env.DOCKER_CTX }} \
            -g ${{ env.AWS_REGION }} \
            -t True
  build-retweet:
    runs-on: ubuntu-20.04
    steps:      
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS credentials from your account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Retweet Lambda Image Build Test
        run: ./scripts/build_push.sh -r mlopsbot/retweets -a ${{ secrets.ACCOUNT_ID }} -c app/lambdaRetweet -g us-east-1 -t True